# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  # For more on hwo this works: https://docs.fastlane.tools/getting-started/ios/running-tests/
  desc "Runs automated unit tests"
  lane :tests do
    run_tests(scheme: "ObjSwiftRefactorExample")
  end
end
